chat:
    art: false
    auto_reply: true
    integrations:
        jira:
            usage: auto
        linear:
            usage: disabled
code_generation:
    docstrings:
        path_instructions: []
    unit_tests:
        path_instructions: []
early_access: false
enable_free_tier: true
knowledge_base:
    code_guidelines:
        enabled: true
        filePatterns:
            - '**/.coderabbit/*'
            - '**/.github/instructions/**'
    issues:
        scope: auto
    jira:
        project_keys: []
        usage: auto
    learnings:
        scope: auto
    linear:
        team_keys: []
        usage: auto
    opt_out: false
    pull_requests:
        scope: auto
    web_search:
        enabled: true
language: en-US
reviews:
    abort_on_close: true
    assess_linked_issues: true
    auto_apply_labels: false
    auto_assign_reviewers: false
    auto_review:
        auto_incremental_review: true
        base_branches: []
        drafts: true
        enabled: true
        ignore_title_keywords: []
        labels: []
    auto_title_instructions: ""
    auto_title_placeholder: '@coderabbitai'
    changed_files_summary: true
    collapse_walkthrough: true
    commit_status: true
    disable_cache: false
    estimate_code_review_effort: true
    fail_commit_status: false
    finishing_touches:
        docstrings:
            enabled: true
        unit_tests:
            enabled: true
    high_level_summary: true
    high_level_summary_in_walkthrough: false
    high_level_summary_placeholder: '@coderabbitai summary'
    in_progress_fortune: true
    labeling_instructions: []
    path_filters: []
    path_instructions: []
    poem: false
    pre_merge_checks: {}
    profile: chill
    related_issues: true
    related_prs: true
    request_changes_workflow: true
    review_status: true
    sequence_diagrams: true
    suggested_labels: true
    suggested_reviewers: true
    tools:
        actionlint:
            enabled: true
        ast-grep:
            essential_rules: true
            packages: []
            rule_dirs: []
            util_dirs: []
        biome:
            enabled: true
        brakeman:
            enabled: true
        buf:
            enabled: true
        checkmake:
            enabled: true
        checkov:
            enabled: true
        circleci:
            enabled: true
        clang:
            enabled: true
        clippy:
            enabled: true
        cppcheck:
            enabled: true
        detekt:
            enabled: true
        dotenvLint:
            enabled: true
        eslint:
            enabled: true
        flake8:
            enabled: true
        github-checks:
            enabled: false
            timeout_ms: 60000
        gitleaks:
            enabled: true
        golangci-lint:
            enabled: true
        hadolint:
            enabled: true
        htmlhint:
            enabled: true
        languagetool:
            disabled_categories: []
            disabled_rules: []
            enabled: true
            enabled_categories: []
            enabled_only: false
            enabled_rules: []
            level: default
        luacheck:
            enabled: true
        markdownlint:
            enabled: true
        osvScanner:
            enabled: true
        oxc:
            enabled: true
        phpcs:
            enabled: true
        phpmd:
            enabled: true
        phpstan:
            enabled: true
            level: default
        pmd:
            enabled: true
        prismaLint:
            enabled: true
        pylint:
            enabled: true
        regal:
            enabled: true
        rubocop:
            enabled: true
        ruff:
            enabled: true
        semgrep:
            enabled: true
        shellcheck:
            enabled: true
        shopifyThemeCheck:
            enabled: true
        sqlfluff:
            enabled: true
        swiftlint:
            enabled: true
        yamllint:
            enabled: true
tone_instructions: ""
